AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  AlarmSNSTopicArn:
    Type: String

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

  LogRetention:
    Type: Number
    Default: 14

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

Resources:

  NotificationStreamManagerLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/log-group.yaml
      Parameters:
        LogGroupName: !Sub ${ProjectName}-notificationStreamManagerLambda
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: /aws/lambda

  EventQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_to_stream'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1

  # internal queues DLQ
  NotificationStreamManagerDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-notification_stream_manager_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"


  # Webhook Notification Table
  StreamNotificationTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-streamNotification'
      AttributeDefinitions:
        - AttributeName: "hashKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "hashKey"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PnStreamLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-stream'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

Outputs:

  StreamNotificationTableName:
    Description: Name of dynamodb table containing
    Value: !Ref StreamNotificationTable
  StreamNotificationTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${StreamNotificationTable.Arn}'

  # Event queue
  EventQueueName:
    Value: !GetAtt EventQueue.Outputs.QueueName
    Description: pn-delivery-push actions done queue name
  EventQueueURL:
    Value: !GetAtt EventQueue.Outputs.QueueURL
    Description: pn-delivery-push actions done queue URL
  EventQueueARN:
    Value: !GetAtt EventQueue.Outputs.QueueARN
    Description: pn-delivery-push actions done queue ARN
  EventQueueAlarmARN:
    Value: !GetAtt EventQueue.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push actions done queue dlq alarm ARN
  EventQueueAgeAlarmARN:
    Value: !GetAtt EventQueue.Outputs.SqsAgeAlarmArn
    Description: pn-delivery-push actions done queue age alarm ARN

  NotificationStreamManagerLambdaName:
    Value: !Sub "${ProjectName}-notificationStreamManagerLambda"

  # Stream Step Manager DLQ
  NotificationStreamManagerName:
    Value: !GetAtt NotificationStreamManagerDLQ.Outputs.QueueName
    Description: pn-delivery-push_webhook_event_manager_DLQ queue name
  NotificationStreamManagerDLQURL:
    Value: !GetAtt NotificationStreamManagerDLQ.Outputs.QueueURL
    Description: pn-delivery-push_webhook_event_manager_DLQ queue URL
  NotificationStreamManagerDLQARN:
    Value: !GetAtt NotificationStreamManagerDLQ.Outputs.QueueARN
    Description: pn-delivery-push_webhook_event_manager_DLQ queue ARN
  NotificationStreamManagerDLQAlarmARN:
    Value: !GetAtt NotificationStreamManagerDLQ.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push_webhook_event_manager_DLQ alarm ARN

  EcsLogGroup:
    Value: !GetAtt PnStreamLogGroup.Outputs.LogGroupName
